---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: busybox-api-image
    newName: registry.hub.docker.com/library/busybox
    newTag: 5effd38
  - name: busybox-db-image
    newName: registry.hub.docker.com/library/postgres
    newTag: 10.11
  - name: busybox-cache-image
    newName: registry.hub.docker.com/library/redis
    newTag: '4.5'
