---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: busybox-api-image
    newName: registry.io/cd-gitops-demo-image-a
    newTag: "cf9854"
  - name: cd-demo-b-image-placeholder
    newName: registry.io/cd-gitops-demo-image-b
    newTag: v1.0.4
