apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox-placeholder
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
