# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_review

name: Auto-approve Pull request against [dev]
on:
  pull_request:
    branches:
    - dev
