on:
  pull_request_target:
    branches:
    - '/refs/heads/dev'
    - 'dev'
  pull_request:
    branches:
    - '/refs/heads/dev'
    - 'dev'
    
jobs:
  deploy_dev:
    #if: contains(github.event.pull_request.labels.*.name, 'dev') && github.event.pull_request.merged == true
    #if: ${{ github.event.label.name == 'dev' }} && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    #environment: 
     # name: development
    steps:
      - name: Deploy to Dev
        run: echo Promote Development
