name: dev1 promote

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'Json payload'
        required: true
        type: string
  workflow_call:
    inputs:
      payload:
        description: 'Json payload'
        required: true
        type: string
        
jobs:
  kustomize-submit-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: 'dev'
      
      - name: Parse payload
        run: |
          echo '${{ inputs.payload }}' | jq > payload.json
          cat payload.json | jq

      - name: Update kustomization.yaml
        run: ./release-update.sh ./payload.json ./deployments/busybox/deployment_id/dev/kustomization.yaml

      - name: Pull Request body
        run: |
          touch pr-body.md
          
          cat <<'EOF' > pr-body.md
          Release PR in `dev` environment

          `/<deployment>/deployment_id/dev/`

          Deployment to `dev1` will take place when this PR is merged 
          
          Comment to promote these changes to **staging** environment:
          - `/bump`
          - `/promote`

          Payload:
          
          EOF

          echo '```json' >> pr-body.md
          cat payload.json | jq >> pr-body.md
          echo '```' >> pr-body.md

      - name: Cleanup files
        run: |
          rm ./payload.json ./pr-body.md
          
      # ToDo: Include deployment name in the pr branch name
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: cicd/bump-dev1
          commit-message: "[cicd] automated change - image update"
          reviewers: lfocorp
          delete-branch: true
          title: '[cicd | dev] promote deployment'
          token: ${{ secrets.GH_TOKEN }}
          labels: cicd, dev
          body-path: pr-body.md

        
