# This is a basic workflow to help you get started with Actions

name: CI Environment Elevator

# Controls when the workflow will run
on:
  issue_comment:
    types: [created, edited]

# should not elevate if PR is not merged
jobs:
  cicd_elevate_environment:
    # This job only runs for pull request comments
    name: Trigger promotion
    #if: contains(github.event.comment.body, '/bump') && github.event.issue.pull_request.merged_at != ''
    if: contains(fromJSON('["/bump", "/promote"]'), github.event.comment.body) && github.event.issue.pull_request.merged_at != ''
    runs-on: ubuntu-latest
    steps:
    - name: Parse JSON payload from PR
      run: |
        export JSON=$(echo '${{ github.event.issue.body }}' | sed -n '/^```/,/^```/ p' | sed '/^```/ d')
        echo $JSON | jq | tee payload.json
        cat payload.json
        export PAYLOAD=$(cat payload.json | jq -c)
        
   # - name: Export Json Payload
   #   run: |
   #   
   #     export PAYLOAD=$(cat payload.json | jq -c)
   #     echo "PAYLOAD=$PAYLOAD >> $GITHUB_ENV
   #     echo "$PAYLOAD"
