# This is a basic workflow to help you get started with Actions

name: CI Elevator

# Controls when the workflow will run
on:
  issue_comment:
    types: [created]

# should not elevate if PR is not merged
jobs:
  pr_elevate:
    # This job only runs for pull request comments
    name: PR comment
    #if: contains(github.event.pull_request.labels.*.name, 'cicd') && github.event.pull_request.merged == true &&  contains(github.event.comment.body, 'promote')
    if: contains(github.event.pull_request.labels.*.name, 'cicd') &&  contains(github.event.comment.body, 'promote')
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve artifact URL 
      run: |
        export URL=$(echo '${{ github.event.issue.body }}' | tail -1)
        export JSON=$(echo '${{ github.event.issue.body }}' | sed -n '/^```/,/^```/ p' | sed '/^```/ d')


        echo $URL
        echo $JSON | jq

        
#    - name: Show artifact URL 
#      run: |
#        echo $ARTIFACT_URL
