name: staging promote

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      payload:
        description: 'Json payload'
        required: true
        type: string
  workflow_call:
    inputs:
      payload:
        description: 'Json payload'
        required: true
        type: string
        
jobs:
  kustomize-submit-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'
      
      - name: Parse payload
        run: |
          echo '${{ inputs.payload }}' | jq > /tmp/payload.json
          cat /tmp/payload.json | jq

      - name: Update kustomization.yaml
        run: ./release-update.sh /tmp/payload.json ./deployments/busybox/deployment_id/staging/kustomization.yaml

      - name: Pull Request body
        run: |
          touch /tmp/pr-body.md
          
          cat <<'EOF' > /tmp/pr-body.md
          Release PR in `staging` environment

          `/<deployment>/deployment_id/staging/`

          Deployment to `staging1` will take place when this PR is merged 
          
          Comment to promote these changes to **staging** environment:
          - `/bump`
          - `/promote`

          Payload:
          
          EOF

          echo '```json' >> /tmp/pr-body.md
          cat /tmp/payload.json | jq >> /tmp/pr-body.md
          echo '```' >> /tmp/pr-body.md
          
      # ToDo: Include deployment name in the pr branch name
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: cicd/bump-staging
          commit-message: "[cicd] image change -  deployment <name>"
          reviewers: lfocorp
          delete-branch: true
          title: '[cicd | staging] promote deployment <name>'
          token: ${{ secrets.GH_TOKEN }}
          labels: cicd, staging
          body-path: /tmp/pr-body.md
