# This is a basic workflow to help you get started with Actions

name: CI Elevator

# Controls when the workflow will run
on:
  issue_comment:
    types: [created, edited]

# should not elevate if PR is not merged
jobs:
  pr_elevate:
    # This job only runs for pull request comments
    name: PR comment
    #if: contains(github.event.comment.body, '/bump') && github.event.issue.pull_request.merged_at != ''
    if: contains(fromJSON('["bump/", "promote/"]'), github.event.comment.body) && github.event.issue.pull_request.merged_at != ''
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve artifact URL 
      run: |
        export URL=$(echo '${{ github.event.issue.body }}' | tail -1)
        export JSON=$(echo '${{ github.event.issue.body }}' | sed -n '/^```/,/^```/ p' | sed '/^```/ d')


        echo $URL
        echo $JSON | jq

        
#    - name: Show artifact URL 
#      run: |
#        echo $ARTIFACT_URL
