on:
  pull_request:
    
jobs:
  deploy_dev:
    #if: contains(github.event.pull_request.labels.*.name, 'dev') && github.event.pull_request.merged == true
    #if: ${{ github.event.label.name == 'dev' }} && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    #environment: 
     # name: development
    steps:
      - name: Deploy to Dev
        if: contains(fromJson('["dev"]'), github.base_ref) && github.head_ref !='staging'
        run: echo Promote Development
