name: dev1 promote

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
    inputs:
      payload:
        description: 'Json payload'
        required: true
        type: string

jobs:
  submit-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: 'dev'
      
      - name: Parse payload
        run: |
          echo '${{ inputs.payload }}' | jq > payload.json
          cat payload.json | jq

      - name: PR body
        run: |
          touch pr-body.md
          
          cat <<'EOF' > pr-body.md
          Release PR            

          EOF

          echo '```json' >> pr-body.md
          cat payload.json | jq >> pr-body.md
          echo '```' >> pr-body.md
 
          
      # ToDo: Include deployment name in the pr branch name
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: cicd/bump-dev1
          commit-message: "[cicd] automated change - image update"
          reviewers: lfocorp
          delete-branch: true
          title: '[CICD] Promote to dev'
          token: ${{ secrets.GH_TOKEN }}
          labels: cicd, dev
          body-path: pr-body.md
    #      body: |
      #      Release PR
       #     
         #   ```
         #   ${{ inputs.payload }}
          #  ```
            
          
