name: staging promote

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_call:
    inputs:
      payload:
        description: 'Json payload'
        required: true
        type: string

jobs:
  submit-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'
      
      - name: Parse payload
        run: |
          echo '${{ inputs.payload }}' | jq > payload.json
          cat payload.json | jq

      - name: PR body
        run: |
          touch pr-body.md
          
          cat <<'EOF' > pr-body.md
          Release PR in `staging` environment

          `/<deployment>/deployment_id/staging/`

          Deployment to `staging` will take place when this PR is merged 
          
          Comment to promote these changes to **production** environment:
          - `bump/`
          - `promote/`

          Payload:
          
          EOF

          echo '```json' >> pr-body.md
          cat payload.json | jq >> pr-body.md
          echo '```' >> pr-body.md
 
          
      # ToDo: Include deployment name in the pr branch name
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: cicd/bump-staging
          commit-message: "[cicd | staging ] automated change <deployment> image update "
          reviewers: lfocorp
          delete-branch: true
          title: '[CICD] Promote to staging'
          token: ${{ secrets.GH_TOKEN }}
          labels: cicd, staging
          body-path: pr-body.md
