on:
  pull_request:


jobs:
  print_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name : Print Title of PR
      env:
          TITLE: ${{ github.event.pull_request.title }}
      run: echo The Title of your PR is $TITLE
    - name : Print Body of PR
      env:
          BODY: ${{ github.event.pull_request.body }}
      run: echo $BODY | tr ' ' '\n'
