# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve artifact URL 
      run: |
        ARTIFACT_URL=${{ github.event.issue.body }} | tail -1)
        export $ARTIFACT_URL

    - name: Show artifact URL 
      run: |
        echo $ARTIFACT_URL
