on:
  workflow_dispatch:
    inputs:
      image_name:
        required: true
        description: Full image URL - registry.hub.docker.com/library/busybox
      image_tag:
        required: true
        description: The image_tag to be promoted
      deployment_name:
        required: true
        description: The deployment in k8s-wb/deployments/<deployment>
      deployment_env:
        required: true
        description: |
          The environment in k8s-wb/deployments/deployment/deployment_id/<environment>
          'production' is catch-all for all regional clusters

        
jobs:
  check-current-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag_current: ${{ steps.check_version.outputs.image_tag_current }}

    steps:
    # Checkout the source code in the repository
    - uses: actions/checkout@v3

    - name: Check the current image_tag
      id: check_version
      env:
        IMAGE_NAME: ${{github.event.inputs.image_name}}
        IMAGE_TAG: ${{github.event.inputs.image_tag}}
        DEPLOYMENT_NAME: ${{github.event.inputs.deployment_name}}
        DEPLOYMENT_ENV: ${{github.event.inputs.deployment_env}}
      run: |
        echo ""
        echo "# Check $IMAGE_NAME version in $DEPLOYMENT_ENV"
        IMAGE_TAG_CURRENT=$(./update-image check)
        echo $IMAGE_TAG_CURRENT
        echo "image_tag_current=$IMAGE_TAG_CURRENT">> "$GITHUB_OUTPUT"

  update-image-tag:
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo ${{needs.check-current-tag.outputs.image_tag_current}}

    # Checkout the source code in the repository
    - uses: actions/checkout@v3

    - name: Print new image information
      run: |
        echo "New image is ${{github.event.inputs.image_name}}:${{github.event.inputs.image_tag}}"
        echo "Deployment is ${{github.event.inputs.deployment_name}} in environment ${{github.event.inputs.deployment_env}}"

    - name: Replace the image_tag
      env:
        IMAGE_NAME: ${{github.event.inputs.image_name}}
        IMAGE_TAG: ${{github.event.inputs.image_tag}}
        DEPLOYMENT_NAME: ${{github.event.inputs.deployment_name}}
        DEPLOYMENT_ENV: ${{github.event.inputs.deployment_env}}

      run: |
        echo $IMAGE_NAME
        echo $IMAGE_TAG
        echo $DEPLOYMENT_NAME
        echo $DEPLOYMENT_ENV
        ./update-image update

    # TODO: condition on change
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      id: create_pull_request
      with:
        title: "Bump ${{github.event.inputs.deployment_name}} version"
        branch: update-image-${{ github.event.inputs.deployment_name }}
        commit-message: Update ${{ github.event.inputs.deployment_name }} image tag - ${{github.event.inputs.image_name}}:${{github.event.inputs.image_tag}}
        token: ${{ secrets.GH_TOKEN }}

    - name: Check outputs
      if: ${{ steps.create_pull_request.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.create_pull_request.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.create_pull_request.outputs.pull-request-url }}"


