on:
  workflow_dispatch:
    inputs:
      image_placeholder:
        required: true
        description: Image placeholder reference, ie. 'busybox-api'
      image_name:
        required: true
        description: The image_name to get promoted
      image_tag:
        required: true
        description: The image_name to get promoted
      deployment_name:
        required: true
        description: The deployment in k8s-wb/deployments/<deployment>
      deployment_env:
        required: true
        description: |
          The environment in k8s-wb/deployments/deployment/deployment_id/<environment>
          'production' is catch-all for all regional clusters

        
jobs:
  test:
    name: Test ${{github.event.inputs.image_name}}:${{github.event.inputs.image_tag}} in ${{github.event.inputs.deployment_env}}
    runs-on: ubuntu-latest
    outputs:
      image_tag_current: ${{ steps.check_version.outputs.image_tag_current }}

    steps:
    # Checkout the source code in the repository
    - uses: actions/checkout@v3

    - name: Check the current image_tag
      id: check_tag
      env:
        IMAGE_NAME: ${{github.event.inputs.image_name}}
        IMAGE_TAG: ${{github.event.inputs.image_tag}}
        DEPLOYMENT_NAME: ${{github.event.inputs.deployment_name}}
        DEPLOYMENT_ENV: ${{github.event.inputs.deployment_env}}
      run: |
        echo ""
        echo "# Check $IMAGE_NAME version in $DEPLOYMENT_ENV"
        ./update-image check >> "$GITHUB_OUTPUT"

  pull-request:
    name: Submit Pull request
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo ${{ needs.check_tag.outputs.image_tag_current }}
        
    # Checkout the source code in the repository
    - uses: actions/checkout@v4

    #- name: Print new image information
    #  run: |
    #    echo "New image is ${{github.event.inputs.image_name}}:${{github.event.inputs.image_tag}}"
    #    echo "Deployment is ${{github.event.inputs.deployment_name}} in environment ${{github.event.inputs.deployment_env}}"

    - name: Replace the image_tag
      env:
        IMAGE_NAME: ${{github.event.inputs.image_name}}
        IMAGE_TAG: ${{github.event.inputs.image_tag}}
        DEPLOYMENT_NAME: ${{github.event.inputs.deployment_name}}
        DEPLOYMENT_ENV: ${{github.event.inputs.deployment_env}}

      run: |
        echo $IMAGE_NAME
        echo $IMAGE_TAG
        echo $DEPLOYMENT_NAME
        echo $DEPLOYMENT_ENV
        ./update-image update

    # TODO: condition on change
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      id: create_pull_request
      with:
        title: "Promote deployment | ${{github.event.inputs.deployment_name}}/${{github.event.inputs.image_placeholder }}:${{github.event.inputs.image_tag}}"
        branch: feat/cicd-promotion-${{ github.event.inputs.deployment_name }}
        commit-message: Promote to ${{ github.event.inputs.deployment_env }} | deployments/${{ github.event.inputs.deployment_name }} image  - ${{github.event.inputs.image_name}}:${{github.event.inputs.image_tag}}
        token: ${{ secrets.GH_TOKEN }}
        labels: ${{ github.event.inputs.deployment_env }},cicd
        delete-branch: true
        body: |
          ```
          image_version="${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}"
          image_placeholder="${{ github.event.inputs.image_placeholder }}"
          deployment="${{ github.event.inputs.deployment_name }}"
          ```
    - name: Pull Request outputs
      if: ${{ steps.create_pull_request.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.create_pull_request.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.create_pull_request.outputs.pull-request-url }}"
        
    - name: Approve Pull Request in dev
      uses: juliangruber/approve-pull-request-action@v2
      if: ${{ github.event.inputs.deployment_env }} == 'dev'
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        number: ${{ steps.create_pull_request.outputs.pull-request-number }}
  
