on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: contains(github.event.pull_request.labels.*.name, 'cicd') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

#    - name : Print Title of PR
#      run: echo The Title of your PR is ${{ github.event.pull_request.title }}

#    - name : Print Description of PR
#      run: echo The Title of your PR is ${{ github.event.pull_request.body }}
