name: dev

on:
  workflow_dispatch:
  repository_dispatch:
    types: 
      - test_result
      - workflow_dispatch
jobs:
  run_if_failure:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
