name: dev

on:
  workflow_dispatch:
    inputs:
      message:
        required: true
        description: A message describing why this workflow is being invoked
      sha:
        required: true
        description: The short hash of the commit the invoked this workflow
      image:
        required: true
        description: The new image, e.g quay.

        
  repository_dispatch:
    types: 
      - test_result
      - workflow_dispatch
jobs:
  run_if_failure:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
