# This is a basic workflow to help you get started with Actions

name: Upload artifact

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
    inputs:
      payload:
        description: 'Json payload'
        required: true
        type: string

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
      artifact-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}

    steps:
      - uses: actions/checkout@v4

      - run: |
          echo '${{ inputs.payload }}' | jq > payload.json
          cat payload.json | jq
          
      - uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          path: payload.json
          name: payload-${{ github.sha }}.json
          
      - name: Output artifact ID
        run: |
          echo 'Artifact ID is ${{ steps.upload-artifact.outputs.artifact-id }}'          
          echo 'Artifact URL is ${{ steps.upload-artifact.outputs.artifact-url }}'
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: cicd/release
          token: ${{ secrets.GH_TOKEN }}
          delete-branch: true
          title: '[Example] PR with artifact URL'
          body: |
            Release PR

            ${{ steps.upload-artifact.outputs.artifact-url }}
          labels: |
            cicd
